### ISSUE TITLE
Compilation failed after upgrading to 5.0.1

### ISSUE THREAD

**Issue by real-artswan** [crisbeto/angular-svg-round-progressbar#212]
It seems module was renamed somewhere between 4.0.0 and 5.0.1 so 
`import { RoundProgressModule } from 'angular-svg-round-progressbar';`
must be 
`import { RoundprogressModule } from 'angular-svg-round-progressbar';`
now.
I think such a breaking change should be mentioned in the readme, also currently readme incorrectly suggests to use the old name.

**Comment by crisbeto** [comment]
Sorry about that, renaming it wasn't intentional. I'll push a new version later today to resolve it.

**Comment by crisbeto** [comment]
Resolved in version 5.0.2.
